export const ActionTypes = {
  REQUEST_EXERCISES: 'REQUEST_EXERCISES',
  RECEIVE_EXERCISES_SUCCESS: 'RECEIVE_EXERCISES_SUCCESS',
  RECEIVE_EXERCISES_ERROR: 'RECEIVE_EXERCISES_ERROR',
  ORDER_EXERCISES: 'ORDER_EXERCISES',
  SET_EXERCISE_DURATION: 'SET_EXERCISE_DURATION',
  FINISH_EXERCISE: 'FINISH_EXERCISE',

  REQUEST_ROUTINES: 'REQUEST_ROUTINES',
  RECEIVE_ROUTINES_SUCCESS: 'RECEIVE_ROUTINES_SUCCESS',
  RECEIVE_ROUTINES_ERROR: 'RECEIVE_ROUTINES_ERROR',
  ORDER_ROUTINES: 'ORDER_ROUTINES',

  START_EXERCISE: 'START_EXERCISE',
  STOP_EXERCISE: 'STOP_EXERCISE',

  API_ERROR: 'API_ERROR',

  // TODO: write a separate account widget
  ACCOUNT_RECEIVE_API_ERROR: 'ACCOUNT_RECEIVE_API_ERROR',
  ACCOUNT_LOGOUT: 'ACCOUNT_LOGOUT',
  ACCOUNT_OPEN_LOGIN_FORM: 'ACCOUNT_OPEN_LOGIN_FORM',
  ACCOUNT_OPEN_REGISTER_FORM: 'ACCOUNT_OPEN_REGISTER_FORM',
  ACCOUNT_OPEN_RESET_FORM: 'ACCOUNT_OPEN_RESET_FORM',
  ACCOUNT_REQUEST_LOGIN: 'ACCOUNT_REQUEST_LOGIN',
  ACCOUNT_RECEIVE_LOGIN_SUCCESS: 'ACCOUNT_RECEIVE_LOGIN_SUCCESS',
  ACCOUNT_REQUEST_REGISTER: 'ACCOUNT_REQUEST_REGISTER',
  ACCOUNT_RECEIVE_REGISTER_SUCCESS: 'ACCOUNT_RECEIVE_REGISTER_SUCCESS',
  ACCOUNT_REQUEST_PASSWORD_RESET: 'ACCOUNT_REQUEST_PASSWORD_RESET',
  ACCOUNT_RECEIVE_PASSWORD_RESET_SUCCESS: 'ACCOUNT_RECEIVE_PASSWORD_RESET_SUCCESS',
}
