export const ActionTypes = {
  REQUEST_EXERCISES: 'REQUEST_EXERCISES',
  RECEIVE_EXERCISES_SUCCESS: 'RECEIVE_EXERCISES_SUCCESS',
  RECEIVE_EXERCISES_ERROR: 'RECEIVE_EXERCISES_ERROR',
  ORDER_EXERCISES: 'ORDER_EXERCISES',
  SET_EXERCISE_DURATION: 'SET_EXERCISE_DURATION',
  FINISH_EXERCISE: 'FINISH_EXERCISE',

  REQUEST_ROUTINES: 'REQUEST_ROUTINES',
  RECEIVE_ROUTINES_SUCCESS: 'RECEIVE_ROUTINES_SUCCESS',
  RECEIVE_ROUTINES_ERROR: 'RECEIVE_ROUTINES_ERROR',
  ORDER_ROUTINES: 'ORDER_ROUTINES',

  START_EXERCISE: 'START_EXERCISE',
  STOP_EXERCISE: 'STOP_EXERCISE',

  API_ERROR: 'API_ERROR',

  ACCOUNT_LOGOUT: 'ACCOUNT_LOGOUT',
  ACCOUNT_OPEN: 'ACCOUNT_OPEN',
  ACCOUNT_REQUEST_LOGIN: 'ACCOUNT_REQUEST_LOGIN',
  ACCOUNT_RECEIVE_LOGIN_SUCCESS: 'ACCOUNT_RECEIVE_LOGIN_SUCCESS',
  ACCOUNT_RECEIVE_LOGIN_ERROR: 'ACCOUNT_RECEIVE_LOGIN_ERROR',
  ACCOUNT_REQUEST_REGISTER: 'ACCOUNT_REQUEST_REGISTER',
  ACCOUNT_RECEIVE_REGISTER_SUCCESS: 'ACCOUNT_RECEIVE_REGISTER_SUCCESS',
  ACCOUNT_RECEIVE_REGISTER_ERROR: 'ACCOUNT_RECEIVE_REGISTER_ERROR',
}
